name: VonixCore
version: '1.1.2'
main: network.vonix.vonixcore.VonixCore
api-version: '1.20' # Using 1.20 to support 1.20+ features but load on 1.18+ (legacy loading might apply, or we assume 1.20+ for api-version usage. Actually, for 1.18 support we might omit this or use 1.18, but Paper 1.21 suggests 1.21. Let's use 1.20 as a safe middle ground or '1.13' for broad compat if we weren't using new features. Paper 1.21 warns if api-version is too old. I'll stick to 1.20 which covers most modern stuff.)
authors: [Vonix Network]
description: Universal VonixCore for Bukkit/Paper

commands:
  vonix:
    description: Main command for VonixCore
    permission: vonix.admin
  sethome:
    description: Set your home
    usage: /sethome [name]
  home:
    description: Teleport to your home
    usage: /home [name]
  delhome:
    description: Delete a home
    usage: /delhome [name]
  homes:
    description: List your homes
    usage: /homes
  warp:
    description: Teleport to a warp
    usage: /warp <name>
  setwarp:
    description: Set a warp
    usage: /setwarp <name>
    permission: vonix.admin
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: vonix.admin
  warps:
    description: List warps
    usage: /warps
  tpa:
    description: Request to teleport to a player
    usage: /tpa <player>
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
  back:
    description: Return to your previous location (death location or last teleport)
    usage: /back
  balance:
    description: Check your balance
    aliases: [bal, money]
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
  kit:
    description: Get a kit
    usage: /kit <name>
  kits:
    description: List kits
    usage: /kits
  createkit:
    description: Create a kit from inventory
    usage: /createkit <name> <delay>
    permission: vonix.admin
  shop:
    description: Open the server shop
    usage: /shop
  cshop:
    description: Chest shop commands
    usage: /cshop <create|remove|info|setprice|buy|sell|find|list>
    aliases: [chestshop, qs, quickshop]
  market:
    description: Player market
    usage: /market [browse|my|create|search|collect]
    aliases: [auction, ah]
  pshop:
    description: Player shop (market)
    usage: /pshop [browse|my|create|search|collect]
    aliases: [playershop]
  shopadmin:
    description: Shop administration
    usage: /shopadmin <reload|stats>
    permission: vonixcore.shops.admin
  jobs:
    description: Jobs system commands
    usage: /jobs <list|join|leave|stats|info|browse>
    aliases: [job]
  co:
    description: CoreProtect-style protection commands
    usage: /co <inspect|lookup|rollback|restore|undo|purge|status|near|help>
    aliases: [coreprotect]
    permission: vonixcore.protection.use
  vp:
    description: VonixCore protection commands
    usage: /vp <inspect|lookup|rollback|restore|undo|purge|status|near|help>
    aliases: [vonixprotect]
    permission: vonixcore.protection.use
  # Authentication commands
  login:
    description: Login to your account
    usage: /login <password>
  register:
    description: Register a new account
    usage: /register [password]
  # Utility commands
  tp:
    description: Teleport to a player
    usage: /tp <player> [target]
    permission: vonixcore.tp
  tphere:
    description: Teleport a player to you
    usage: /tphere <player>
    permission: vonixcore.tphere
  tppos:
    description: Teleport to coordinates
    usage: /tppos <x> <y> <z>
    permission: vonixcore.tppos
  tpall:
    description: Teleport all players to you
    usage: /tpall
    permission: vonixcore.tpall
  rtp:
    description: Random teleport
    usage: /rtp
    permission: vonixcore.rtp
  nick:
    description: Set your nickname
    usage: /nick [name]
    permission: vonixcore.nick
  seen:
    description: Check when a player was last online
    usage: /seen <player>
  whois:
    description: View player information
    usage: /whois <player>
  ping:
    description: Check your ping
    usage: /ping
  near:
    description: View nearby players
    usage: /near [radius]
  getpos:
    description: Get your coordinates
    usage: /getpos
    aliases: [pos, coords]
  playtime:
    description: View your playtime
    usage: /playtime
  msg:
    description: Send a private message
    usage: /msg <player> <message>
    aliases: [tell, whisper, w]
  r:
    description: Reply to a private message
    usage: /r <message>
    aliases: [reply]
  ignore:
    description: Ignore a player
    usage: /ignore <player>
  heal:
    description: Heal a player
    usage: /heal [player]
    permission: vonixcore.heal
  feed:
    description: Feed a player
    usage: /feed [player]
    permission: vonixcore.feed
  fly:
    description: Toggle fly mode
    usage: /fly [player]
    permission: vonixcore.fly
  god:
    description: Toggle god mode
    usage: /god [player]
    permission: vonixcore.god
  speed:
    description: Set walk/fly speed
    usage: /speed <0-10>
    permission: vonixcore.speed
  clear:
    description: Clear inventory
    usage: /clear [player]
    aliases: [clearinventory, ci]
    permission: vonixcore.clear
  repair:
    description: Repair held item
    usage: /repair
    permission: vonixcore.repair
  more:
    description: Fill item stack
    usage: /more
    permission: vonixcore.more
  hat:
    description: Wear item as hat
    usage: /hat
    permission: vonixcore.hat
  broadcast:
    description: Broadcast a message
    usage: /broadcast <message>
    aliases: [bc]
    permission: vonixcore.broadcast
  invsee:
    description: View player inventory
    usage: /invsee <player>
    permission: vonixcore.invsee
  enderchest:
    description: Open ender chest
    usage: /enderchest [player]
    aliases: [ec]
    permission: vonixcore.enderchest
  workbench:
    description: Open crafting table
    usage: /workbench
    aliases: [craft]
  gc:
    description: View server stats
    usage: /gc
    permission: vonixcore.gc
  lag:
    description: View server TPS
    usage: /lag

  vonixcoreclaims:
    description: Land claim system
    usage: /vonixcoreclaims <wand|create|delete|trust|untrust|list|info|admin>
    aliases: [vcclaims, claims]

permissions:
  vonixcore.shop:
    description: Access to server shop
    default: true
  vonixcore.shops.create:
    description: Create chest shops
    default: true
  vonixcore.shops.unlimited:
    description: Bypass shop limits
    default: op
  vonixcore.shops.admin:
    description: Shop administration
    default: op
  vonixcore.shops.admin.remove:
    description: Remove any shop
    default: op
  vonixcore.market:
    description: Access to player market
    default: true
  vonixcore.market.unlimited:
    description: Bypass market limits
    default: op
  vonixcore.jobs:
    description: Access to jobs system
    default: true
  vonixcore.jobs.unlimited:
    description: Bypass job limits
    default: op
  vonixcore.jobs.admin:
    description: Jobs administration
    default: op
  vonixcore.protection.use:
    description: Use protection commands
    default: op
  vonixcore.protection.inspect:
    description: Use inspector mode
    default: op
  vonixcore.protection.lookup:
    description: Lookup block history
    default: op
  vonixcore.protection.rollback:
    description: Rollback changes
    default: op
  vonixcore.protection.restore:
    description: Restore changes
    default: op
  vonixcore.protection.purge:
    description: Purge old data
    default: op
  vonixcore.claims.create:
    description: Create land claims
    default: true
  vonixcore.claims.admin:
    description: Admin claims (bypass protection, delete any)
    default: op

