name: VonixCore
version: '${version}'
main: network.vonix.vonixcore.VonixCore
api-version: '1.20' # Using 1.20 to support 1.20+ features but load on 1.18+ (legacy loading might apply, or we assume 1.20+ for api-version usage. Actually, for 1.18 support we might omit this or use 1.18, but Paper 1.21 suggests 1.21. Let's use 1.20 as a safe middle ground or '1.13' for broad compat if we weren't using new features. Paper 1.21 warns if api-version is too old. I'll stick to 1.20 which covers most modern stuff.)
authors: [Vonix Network]
description: Universal VonixCore for Bukkit/Paper

commands:
  vonix:
    description: Main command for VonixCore
    permission: vonix.admin
  sethome:
    description: Set your home
    usage: /sethome [name]
  home:
    description: Teleport to your home
    usage: /home [name]
  delhome:
    description: Delete a home
    usage: /delhome [name]
  homes:
    description: List your homes
    usage: /homes
  warp:
    description: Teleport to a warp
    usage: /warp <name>
  setwarp:
    description: Set a warp
    usage: /setwarp <name>
    permission: vonix.admin
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: vonix.admin
  warps:
    description: List warps
    usage: /warps
  tpa:
    description: Request to teleport to a player
    usage: /tpa <player>
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
  rtp:
    description: Random teleport
    usage: /rtp
    permission: vonixcore.rtp
  tphere:
    description: Teleport a player to you
    usage: /tphere <player>
    permission: vonixcore.tphere
  tpall:
    description: Teleport all players to you
    usage: /tpall
    permission: vonixcore.tpall
  tppos:
    description: Teleport to coordinates
    usage: /tppos <x> <y> <z>
    permission: vonixcore.tppos
  setspawn:
    description: Set the world spawn point
    usage: /setspawn
    permission: vonixcore.setspawn
  spawn:
    description: Teleport to spawn
    usage: /spawn
  register:
    description: Register an account
    usage: /register <password> <confirm>
  login:
    description: Log in to your account
    usage: /login <password>
  logout:
    description: Log out of your account
    usage: /logout
  changepassword:
    description: Change your password
    usage: /changepassword <old> <new>
  nick:
    description: Set your nickname
    usage: /nick <name|off>
    permission: vonixcore.nick
  hat:
    description: Wear item as hat
    usage: /hat
    permission: vonixcore.hat
  more:
    description: Max out item stack
    usage: /more
    permission: vonixcore.more
  repair:
    description: Repair held item
    usage: /repair
    permission: vonixcore.repair
  playtime:
    description: Check playtime
    usage: /playtime [player]
  whois:
    description: Check player info
    usage: /whois <player>
    permission: vonixcore.whois
  seen:
    description: Check last seen
    usage: /seen <player>
  clear:
    description: Clear inventory
    usage: /clear [player]
    permission: vonixcore.clear
  balance:
    description: Check your balance
    aliases: [bal, money]
  time:
    description: Set time
    usage: /time <value>
    permission: vonixcore.time
  weather:
    description: Set weather
    usage: /weather <value>
    permission: vonixcore.weather
  day:
    description: Set to day
    permission: vonixcore.time
  night:
    description: Set to night
    permission: vonixcore.time
  sun:
    description: Set to sun
    permission: vonixcore.weather
  rain:
    description: Set to rain
    permission: vonixcore.weather
  storm:
    description: Set to storm
    permission: vonixcore.weather
  heal:
    description: Heal player
    usage: /heal [player]
    permission: vonixcore.heal
  feed:
    description: Feed player
    usage: /feed [player]
    permission: vonixcore.feed
  fly:
    description: Toggle flight
    usage: /fly
    permission: vonixcore.fly
  god:
    description: Toggle god mode
    usage: /god
    permission: vonixcore.god
  afk:
    description: Toggle AFK
    usage: /afk
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
  kit:
    description: Get a kit
    usage: /kit <name>
  kits:
    description: List kits
    usage: /kits
  createkit:
    description: Create a kit from inventory
    usage: /createkit <name> <delay>
    permission: vonix.admin
  shop:
    description: Open the server shop
    usage: /shop
  cshop:
    description: Chest shop commands
    usage: /cshop <create|remove|info|setprice|buy|sell|find|list>
    aliases: [chestshop, qs, quickshop]
  market:
    description: Player market
    usage: /market [browse|my|create|search|collect]
    aliases: [auction, ah]
  pshop:
    description: Player shop (market)
    usage: /pshop [browse|my|create|search|collect]
    aliases: [playershop]
  shopadmin:
    description: Shop administration
    usage: /shopadmin <reload|stats>
    permission: vonixcore.shops.admin
  jobs:
    description: Jobs system commands
    usage: /jobs <list|join|leave|stats|info|browse>
    aliases: [job]

permissions:
  vonixcore.shop:
    description: Access to server shop
    default: true
  vonixcore.shops.create:
    description: Create chest shops
    default: true
  vonixcore.shops.unlimited:
    description: Bypass shop limits
    default: op
  vonixcore.shops.admin:
    description: Shop administration
    default: op
  vonixcore.shops.admin.remove:
    description: Remove any shop
    default: op
  vonixcore.market:
    description: Access to player market
    default: true
  vonixcore.market.unlimited:
    description: Bypass market limits
    default: op
  vonixcore.jobs:
    description: Access to jobs system
    default: true
  vonixcore.jobs.unlimited:
    description: Bypass job limits
    default: op
  vonixcore.jobs.admin:
    description: Jobs administration
    default: op
