name: VonixCore
version: '${version}'
main: network.vonix.vonixcore.VonixCore
api-version: '1.20' # Using 1.20 to support 1.20+ features but load on 1.18+ (legacy loading might apply, or we assume 1.20+ for api-version usage. Actually, for 1.18 support we might omit this or use 1.18, but Paper 1.21 suggests 1.21. Let's use 1.20 as a safe middle ground or '1.13' for broad compat if we weren't using new features. Paper 1.21 warns if api-version is too old. I'll stick to 1.20 which covers most modern stuff.)
authors: [Vonix Network]
description: Universal VonixCore for Bukkit/Paper

commands:
  vonix:
    description: Main command for VonixCore
    permission: vonix.admin
  sethome:
    description: Set your home
    usage: /sethome [name]
  home:
    description: Teleport to your home
    usage: /home [name]
  delhome:
    description: Delete a home
    usage: /delhome [name]
  homes:
    description: List your homes
    usage: /homes
  warp:
    description: Teleport to a warp
    usage: /warp <name>
  setwarp:
    description: Set a warp
    usage: /setwarp <name>
    permission: vonix.admin
  delwarp:
    description: Delete a warp
    usage: /delwarp <name>
    permission: vonix.admin
  warps:
    description: List warps
    usage: /warps
  tpa:
    description: Request to teleport to a player
    usage: /tpa <player>
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
  balance:
    description: Check your balance
    aliases: [bal, money]
  pay:
    description: Pay a player
    usage: /pay <player> <amount>
  kit:
    description: Get a kit
    usage: /kit <name>
  kits:
    description: List kits
    usage: /kits
  createkit:
    description: Create a kit from inventory
    usage: /createkit <name> <delay>
    permission: vonix.admin
