database:
  type: sqlite
  sqlite:
    file: vonixcore.db
  mysql:
    host: localhost
    port: 3306
    database: vonixcore
    username: root
    password: ""
  postgresql:
    host: localhost
    port: 5432
    database: vonixcore
    username: postgres
    password: ""
  supabase:
    host: db.xxxxxxxxxxxx.supabase.co
    port: 5432
    database: postgres
    password: ""
  turso:
    url: libsql://your-database.turso.io
    auth_token: ""
  pool:
    max_connections: 10
    timeout_ms: 5000
  performance:
    batch_size: 500
    batch_delay_ms: 500
    purge_days: 30
